"""
ml_classifier.py — Strata Cadastre (SIH26011)
Automated building extraction via supervised machine learning.

Closes the problem statement's "AI/ML capabilities → Automated building
extraction" requirement with an actual trained model, not a heuristic.

WHAT THIS IS
------------
A Random Forest classifier that labels every LiDAR point as ground,
building, or vegetation, using eight geometric features computed from each
point's local neighbourhood. This is the standard feature-engineering
approach for airborne LiDAR classification — the features below (height
above local ground, PCA-derived planarity/linearity/sphericity,
verticality, density, height variance) are the ones the remote-sensing
literature consistently finds most discriminative for this task.

WHY THIS REPLACES classify_ground_points()
------------------------------------------
pipeline.py's classify_ground_points() is a cell-minimum heuristic: it can
only separate "low" from "high". It cannot tell a tree from a building,
because both are high. That distinction matters here — vegetation
misclassified as building inflates extracted footprints and corrupts every
downstream volume, ULPIN and tax figure.

The heuristic remains in pipeline.py as a dependency-free fallback. This
module is the upgrade path, and both are kept deliberately: if scikit-learn
won't install on demo day, ingestion still works.

HONEST SCOPE
------------
- Trained on SYNTHETIC data generated by this module (real labelled LiDAR
  for Ahmedabad was not obtainable — see ingest_real.py's docstring). The
  model is real, the training pipeline is real, the metrics below are real
  and measured on a held-out split; the *data* is simulated. Retrain on
  real labelled tiles (OpenTopography publishes classified LAS) before
  claiming field accuracy.
- Random Forest, not deep learning. Deliberate: with ~10k training points
  and 8 engineered features, a forest beats a small CNN and trains in
  seconds on a laptop. Point-cloud deep learning (PointNet++, KPConv)
  needs far more labelled data than a hackathon can produce, and a badly
  trained network is worse than a well-chosen classical model.
"""

from __future__ import annotations

import pickle
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

CLASS_GROUND = 2
CLASS_VEGETATION = 5
CLASS_BUILDING = 6

CLASS_NAMES = {
    CLASS_GROUND: "ground",
    CLASS_VEGETATION: "vegetation",
    CLASS_BUILDING: "building",
}

FEATURE_NAMES = [
    "height_above_cell_min",
    "height_above_neighbourhood_min",
    "planarity",
    "linearity",
    "sphericity",
    "verticality",
    "neighbourhood_density",
    "local_height_std",
]


# ============================================================================
# Feature extraction
# ============================================================================

def compute_features(points_xyz: np.ndarray, k: int = 20, radius: float = 3.0,
                      cell_size: float = 1.0) -> np.ndarray:
    """Compute the 8-feature descriptor for every point.

    points_xyz: (N, 3) array in local ENU metres.
    Returns: (N, 8) float array, column order matching FEATURE_NAMES.

    The PCA features come from the eigenvalues of each point's local
    covariance, sorted descending (l1 >= l2 >= l3):
      planarity   = (l2 - l3) / l1   → high on flat surfaces (roofs, ground)
      linearity   = (l1 - l2) / l1   → high on edges and wires
      sphericity  = l3 / l1          → high on scattered volumes (foliage)
    Vegetation is scattered, so it scores high sphericity and low
    planarity. That single contrast is what the heuristic cannot see and
    is most of why this model works.
    """
    points_xyz = np.asarray(points_xyz, dtype=np.float64)
    n = len(points_xyz)
    if n == 0:
        return np.zeros((0, len(FEATURE_NAMES)))

    x, y, z = points_xyz[:, 0], points_xyz[:, 1], points_xyz[:, 2]
    features = np.zeros((n, len(FEATURE_NAMES)), dtype=np.float64)

    # --- 1. Height above the minimum Z in this point's grid cell ---
    cell_x = np.floor(x / cell_size).astype(np.int64)
    cell_y = np.floor(y / cell_size).astype(np.int64)
    cell_key = pd.Series(list(zip(cell_x, cell_y)))
    cell_min = pd.DataFrame({"key": cell_key, "z": z}).groupby("key")["z"].transform("min").to_numpy()
    features[:, 0] = z - cell_min

    # --- KD-trees: 2D for the ground reference, 3D for shape ---
    tree_2d = cKDTree(points_xyz[:, :2])
    tree_3d = cKDTree(points_xyz)

    # --- 2. Height above the lowest point within `radius` horizontally ---
    neighbours_2d = tree_2d.query_ball_point(points_xyz[:, :2], r=radius)
    height_above_local = np.empty(n)
    density = np.empty(n)
    for i, idx in enumerate(neighbours_2d):
        height_above_local[i] = z[i] - z[idx].min()
        density[i] = len(idx)
    features[:, 1] = height_above_local
    features[:, 6] = density

    # --- 3-6. PCA shape descriptors over the k nearest 3D neighbours ---
    k_eff = min(k, n)
    _, knn_idx = tree_3d.query(points_xyz, k=k_eff)
    if knn_idx.ndim == 1:
        knn_idx = knn_idx.reshape(-1, 1)

    neighbourhoods = points_xyz[knn_idx]                     # (n, k, 3)
    centred = neighbourhoods - neighbourhoods.mean(axis=1, keepdims=True)
    cov = np.einsum("nki,nkj->nij", centred, centred) / max(1, k_eff - 1)

    eigenvalues, eigenvectors = np.linalg.eigh(cov)          # ascending
    eigenvalues = np.clip(eigenvalues[:, ::-1], 1e-12, None)  # descending, positive
    eigenvectors = eigenvectors[:, :, ::-1]

    l1, l2, l3 = eigenvalues[:, 0], eigenvalues[:, 1], eigenvalues[:, 2]
    features[:, 2] = (l2 - l3) / l1        # planarity
    features[:, 3] = (l1 - l2) / l1        # linearity
    features[:, 4] = l3 / l1               # sphericity

    # Verticality from the surface normal (smallest-eigenvalue eigenvector).
    # A vertical wall has a horizontal normal → |n_z| near 0 → verticality
    # near 1. A flat roof or ground has |n_z| near 1 → verticality near 0.
    normals = eigenvectors[:, :, 2]
    features[:, 5] = 1.0 - np.abs(normals[:, 2])

    # --- 8. Local height spread, a strong vegetation cue ---
    features[:, 7] = neighbourhoods[:, :, 2].std(axis=1)

    return features


# ============================================================================
# Synthetic labelled training data
# ============================================================================

def generate_training_cloud(seed: int = 17) -> Tuple[np.ndarray, np.ndarray]:
    """Build a labelled point cloud containing all three classes.

    Deliberately harder than pipeline.py's demo scene: the trees are the
    same height as the lower storeys, so height alone cannot separate
    vegetation from building. A model that scores well here has genuinely
    learned shape, not just elevation.
    """
    rng = np.random.default_rng(seed)
    points, labels = [], []

    # --- Ground: a gently undulating surface ---
    n_ground = 6000
    gx = rng.uniform(-45, 45, n_ground)
    gy = rng.uniform(-45, 45, n_ground)
    gz = 0.4 * np.sin(gx / 18) + 0.3 * np.cos(gy / 22) + rng.normal(0, 0.03, n_ground)
    points.append(np.column_stack([gx, gy, gz]))
    labels.append(np.full(n_ground, CLASS_GROUND))

    # --- Buildings: planar walls and roofs ---
    building_specs = [
        (-15, -10, 15, 11, 19.2),
        (18, 14, 12, 14, 12.8),
        (-24, 20, 16, 10, 9.6),
    ]
    for cx, cy, w, d, height in building_specs:
        x0, x1 = cx - w / 2, cx + w / 2
        y0, y1 = cy - d / 2, cy + d / 2

        n_roof = int(w * d * 5)
        rx = rng.uniform(x0, x1, n_roof)
        ry = rng.uniform(y0, y1, n_roof)
        rz = np.full(n_roof, height) + rng.normal(0, 0.02, n_roof)
        points.append(np.column_stack([rx, ry, rz]))
        labels.append(np.full(n_roof, CLASS_BUILDING))

        for (ax, ay, bx, by) in [(x0, y0, x1, y0), (x1, y0, x1, y1),
                                   (x1, y1, x0, y1), (x0, y1, x0, y0)]:
            length = float(np.hypot(bx - ax, by - ay))
            n_wall = int(length * height * 4)
            t = rng.uniform(0, 1, n_wall)
            wx = ax + t * (bx - ax) + rng.normal(0, 0.02, n_wall)
            wy = ay + t * (by - ay) + rng.normal(0, 0.02, n_wall)
            wz = rng.uniform(0, height, n_wall)
            points.append(np.column_stack([wx, wy, wz]))
            labels.append(np.full(n_wall, CLASS_BUILDING))

    # --- Vegetation: scattered ellipsoidal canopies, no planar structure ---
    tree_positions = [(5, -28, 6.0), (-32, -20, 7.5), (30, -8, 5.5), (-6, 30, 8.0),
                       (12, 34, 6.5), (-38, 4, 7.0), (36, 30, 6.0), (0, -40, 5.0),
                       (22, -34, 6.8), (-18, -36, 7.2)]
    for tx, ty, canopy_top in tree_positions:
        n_canopy = rng.integers(500, 900)
        # Uniform-in-ball sampling, then squashed into an ellipsoid.
        u = rng.normal(0, 1, (n_canopy, 3))
        u /= np.linalg.norm(u, axis=1, keepdims=True)
        r = rng.random(n_canopy) ** (1 / 3)
        blob = u * r[:, None] * np.array([2.6, 2.6, 1.9])
        cx_ = tx + blob[:, 0]
        cy_ = ty + blob[:, 1]
        cz_ = canopy_top + blob[:, 2] + rng.normal(0, 0.25, n_canopy)
        points.append(np.column_stack([cx_, cy_, cz_]))
        labels.append(np.full(n_canopy, CLASS_VEGETATION))

        n_trunk = 40
        points.append(np.column_stack([
            tx + rng.normal(0, 0.12, n_trunk),
            ty + rng.normal(0, 0.12, n_trunk),
            rng.uniform(0, canopy_top - 1.5, n_trunk),
        ]))
        labels.append(np.full(n_trunk, CLASS_VEGETATION))

    return np.vstack(points), np.concatenate(labels)


# ============================================================================
# Model
# ============================================================================

class PointCloudClassifier:
    """Random Forest classifier over the 8 geometric features above."""

    def __init__(self, n_estimators: int = 120, max_depth: Optional[int] = 18,
                 random_state: int = 42):
        from sklearn.ensemble import RandomForestClassifier
        self.model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            random_state=random_state,
            n_jobs=-1,
            class_weight="balanced",   # vegetation is the minority class
        )
        self.is_trained = False

    def fit(self, points_xyz: np.ndarray, labels: np.ndarray) -> "PointCloudClassifier":
        features = compute_features(points_xyz)
        self.model.fit(features, labels)
        self.is_trained = True
        return self

    def predict(self, points_xyz: np.ndarray) -> np.ndarray:
        """Classify points.

        IMPORTANT: every feature is computed from a point's LOCAL
        NEIGHBOURHOOD, so a point's classification depends on which other
        points you pass in alongside it. Classifying a subset in isolation
        will not reproduce the labels that subset received as part of the
        full cloud — always classify a complete, spatially contiguous
        cloud, and subsample with ingest_real.subsample() (which thins
        uniformly) rather than by slicing off a corner.
        """
        if not self.is_trained:
            raise RuntimeError("Classifier is not trained — call fit() or load() first.")
        return self.model.predict(compute_features(points_xyz))

    def predict_dataframe(self, df: pd.DataFrame) -> pd.DataFrame:
        """Classify a pipeline.py-style DataFrame, returning a copy whose
        `classification` column holds the predicted ASPRS codes."""
        xyz = df[["x", "y", "z"]].to_numpy()
        out = df.copy()
        out["classification"] = self.predict(xyz)
        return out

    def feature_importances(self) -> Dict[str, float]:
        if not self.is_trained:
            raise RuntimeError("Classifier is not trained.")
        return dict(sorted(
            zip(FEATURE_NAMES, self.model.feature_importances_),
            key=lambda kv: kv[1], reverse=True,
        ))

    def save(self, path: str | Path) -> None:
        with open(path, "wb") as fh:
            pickle.dump(self.model, fh)

    @classmethod
    def load(cls, path: str | Path) -> "PointCloudClassifier":
        obj = cls.__new__(cls)
        with open(path, "rb") as fh:
            obj.model = pickle.load(fh)
        obj.is_trained = True
        return obj


def extract_building_points(df: pd.DataFrame, classifier: PointCloudClassifier) -> pd.DataFrame:
    """Automated building extraction: classify, then keep only building
    points. This is what feeds footprint extraction and floor delineation
    downstream, with vegetation removed rather than silently inflating the
    building envelope."""
    classified = classifier.predict_dataframe(df)
    return classified[classified["classification"] == CLASS_BUILDING].reset_index(drop=True)


# ============================================================================
# Training + evaluation
# ============================================================================

def train_and_evaluate(test_size: float = 0.3, seed: int = 17) -> Tuple[PointCloudClassifier, Dict]:
    """Train on a held-out split and report honest metrics.

    The split is spatial-free (random over points), which is the standard
    approach for per-point classification but does mean neighbouring points
    can land on both sides of the split. Real-world accuracy on unseen
    tiles will be lower than the numbers below.
    """
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

    points, labels = generate_training_cloud(seed)
    features = compute_features(points)

    X_train, X_test, y_train, y_test = train_test_split(
        features, labels, test_size=test_size, random_state=seed, stratify=labels
    )

    classifier = PointCloudClassifier()
    classifier.model.fit(X_train, y_train)
    classifier.is_trained = True

    y_pred = classifier.model.predict(X_test)

    metrics = {
        "n_points": len(points),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "report": classification_report(
            y_test, y_pred,
            labels=[CLASS_GROUND, CLASS_VEGETATION, CLASS_BUILDING],
            target_names=["ground", "vegetation", "building"],
            zero_division=0,
        ),
        "confusion_matrix": confusion_matrix(
            y_test, y_pred, labels=[CLASS_GROUND, CLASS_VEGETATION, CLASS_BUILDING]
        ),
        "feature_importances": classifier.feature_importances(),
    }
    return classifier, metrics


if __name__ == "__main__":
    print("=" * 76)
    print("ml_classifier.py — automated building extraction (supervised ML)")
    print("=" * 76)

    print("\nGenerating labelled training cloud...")
    classifier, metrics = train_and_evaluate()

    print(f"  {metrics['n_points']:,} points  "
          f"({metrics['n_train']:,} train / {metrics['n_test']:,} held-out test)")

    print(f"\n--- Held-out accuracy: {metrics['accuracy'] * 100:.2f}% ---")
    print(metrics["report"])

    print("Confusion matrix (rows = true, cols = predicted)")
    print("                ground  vegetation  building")
    names = ["ground    ", "vegetation", "building  "]
    for name, row in zip(names, metrics["confusion_matrix"]):
        print(f"  {name}  {row[0]:>6}  {row[1]:>10}  {row[2]:>8}")

    print("\n--- Feature importances ---")
    for feature, importance in classifier.feature_importances().items():
        bar = "#" * int(importance * 60)
        print(f"  {feature:<32} {importance:.4f}  {bar}")

    print("\n--- Building extraction on an unseen scene ---")
    points, true_labels = generate_training_cloud(seed=99)
    df = pd.DataFrame(points, columns=["x", "y", "z"])
    df["classification"] = true_labels

    extracted = extract_building_points(df, classifier)
    true_building = int((true_labels == CLASS_BUILDING).sum())
    predicted = classifier.predict(points)

    true_positive = int(((predicted == CLASS_BUILDING) & (true_labels == CLASS_BUILDING)).sum())
    false_positive = int(((predicted == CLASS_BUILDING) & (true_labels != CLASS_BUILDING)).sum())
    false_negative = int(((predicted != CLASS_BUILDING) & (true_labels == CLASS_BUILDING)).sum())
    precision = true_positive / max(1, true_positive + false_positive)
    recall = true_positive / max(1, true_positive + false_negative)

    print(f"  scene has {len(df):,} points, {true_building:,} truly building")
    print(f"  extracted {len(extracted):,} building points")
    print(f"  precision {precision * 100:.2f}%  ·  recall {recall * 100:.2f}%  "
          f"·  F1 {200 * precision * recall / max(1e-9, precision + recall):.2f}%")

    veg_as_building = int(((predicted == CLASS_BUILDING) & (true_labels == CLASS_VEGETATION)).sum())
    total_veg = int((true_labels == CLASS_VEGETATION).sum())
    print(f"  vegetation misread as building: {veg_as_building} of {total_veg:,} "
          f"({100 * veg_as_building / max(1, total_veg):.2f}%)")

    model_path = Path("strata_point_classifier.pkl")
    classifier.save(model_path)
    reloaded = PointCloudClassifier.load(model_path)

    # Compare on an IDENTICAL feature matrix. Features are neighbourhood-
    # dependent, so re-running compute_features() on a subset of the same
    # cloud legitimately yields different values — comparing predictions
    # across two different feature matrices would test nothing.
    features_all = compute_features(points)
    match = bool((reloaded.model.predict(features_all)
                  == classifier.model.predict(features_all)).all())
    print(f"\n  model saved to {model_path.name} and reloaded identically: {match}")
    assert match, "model did not survive the save/load round trip"

    print("\n" + "=" * 76)
    print("Training complete.")
    print("=" * 76)
